#! /usr/bin/env python
 
import rospy
from geometry_msgs.msg import Twist
from sensor_msgs.msg import LaserScan
import time
ls = LaserScan()
global aa   
global bb 
global cc

def callback(msg):
    # print len(msg.ranges)
    # values at 0 degree
    print("left lazer is")
    a = msg.ranges[0]
    aa = a
    print(a)
    print("\n")
    # values at 90 degree
    print("center lazer is")
    b = msg.ranges[360]
    bb = b
    print msg.ranges[360]
    print("\n")
    # values at 180 degree
    print("right lazer is")
    # global c = msg.ranges[719]
    print msg.ranges[719]
    print("\n")
    time.sleep(2)
    
    
 
rospy.init_node('quiz1_package')
pub = rospy.Publisher('/cmd_vel', Twist, queue_size=1) #Create a Publisher that will publish in the /age_info topic
sub = rospy.Subscriber('/kobuki/laser/scan', LaserScan, callback)
# rospy.spin()
rate = rospy.Rate(2)
move_left = Twist()
print("Twist assignment")

print(bbb)

move_left.linear.x = 0.5 #Move the robot with a linear velocity in the x axis
move_left.angular.z = 0.5 #Move the with an angular velocity in the z axis
# move.linear.x = 0.5 #Move the robot with a linear velocity in the x axis
# move.angular.z = 0.5 #Move the with an angular velocity in the z axis
# if bb > 1:
#     print('ITS GLOBAL!!')


while not rospy.is_shutdown(): 
  pub.publish(move_left)
  rate.sleep()

